[build]
  publish = "."
  command = "echo 'Derleme adımı yok'"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# /gizlilik → gizlilik.html
[[redirects]]
  from = "/gizlilik"
  to = "/gizlilik.html"
  status = 200
